### ISSUE TITLE
Broken Link for Submission Confirmation

### ISSUE THREAD

**Issue by egregoss** [yeldiRium/st3k101#108]
The link in the email send to the users after their submission is broken:
>
Hi there!
You've recently participated in the survey Coolness.
To confirm your submission, please follow the link below:

http://https://survey.edutec.guru/api/response/verify/659a4dfc9289a292d1a7ec2fc9baf18a
<

In the backend.env the domain is set as:
DOMAIN_NAME=https://survey.edutec.guru

**Comment by strangedev** [comment]
Yes, this happens because the `DOMAIN_NAME` environment variable should not contain a protocol specification.

This case should be detected when building the URL nevertheless.
