### ISSUE TITLE
local frontend caches bundles?

### ISSUE THREAD

**Issue by yeldiRium** [yeldiRium/st3k101#39]
When I update the bundle, the frontend does not seem to change, even after `Ctrl+Shift+R`.

**Comment by strangedev** [comment]
According to the ExpressJS documentation for express 4.x, there is no caching for static files.

```
NOTE: For best results, use a reverse proxy cache to improve performance of serving static assets.
```
(From http://expressjs.com/en/4x/api.html)

**Comment by yeldiRium** [comment]
Problem did not occur again on next try. Dropping the issue.
