### ISSUE TITLE
Questionnaire: Differentiate between `published` and `accepts_submissions`

### ISSUE THREAD

**Issue by strangedev** [yeldiRium/st3k101#53]
Whether a survey is published or it accepts new submissions are semantically different things.

When a survey is not published, the API won't deliver it to the frontend, thus it, or any information about it cannot be displayed.

When a survey is published, but does not accept new submissions, it will be delivered by the API and the frontend may render information about it, yet there's no way to submit.

### Use Cases

1. Embedding a survey before accepting submissions

A DataClient may choose to embed the survey before they intend to collect data on it. At the moment, a DataClient can't verify that the embedding was successful without also accepting submissions by anyone who has access to the course where the survey is embedded. Usually, course content is set up before the course starts, so the embedded survey should start out published, but only display some generic information about the survey alongside an information text, detailing that the survey can't be taken yet.

2. Concluding a survey

At the moment, when a DataClient decides not to accept new submission anymore, they have to retract the survey, which will break all existing links and embeddings, as the frontend can't gather any information about surveys that are not published.

### Proposed changes

1. Add `accepts_submissions` flag to Questionnaire
2. Update `*SurveyForSubmission` components to recognize the new flag and only display a landing page
3. Update API to only accept submission, if the `accept_submissions` flag is set
4. Update the frontend to allow setting of this flag.

**Comment by yeldiRium** [comment]
I agree with the proposition.
I only have one concern: `published: false, accepts_submissions: true` seems invalid to me.

So we'd have to ignore the `accepts_submissions` flag, as long as `published` ist false. Or have the setter for `published` set `accepts_submissions` to false, when `published` is set to false.

**Comment by strangedev** [comment]
resolved by #66
